export const ORDER_MODAL_TEXT = {
    HEADER: "Hacer una orden para",
    ORDER_TYPE: "Tipo de orden:",
    BUY: "BUY",
    SELL: "SELL",
    ORDER_METHOD: "Tipo de orden (MARKET o LIMIT):",
    MARKET: "MARKET",
    LIMIT: "LIMIT",
    QUANTITY: "Cantidad:",
    PRICE: "Precio:",
    INVESTMENT_AMOUNT: "Inversión total (en pesos):",
    SUBMIT_ORDER: "Enviar Orden",
    CANCEL: "Cancelar",
    ERROR: "Error",
    ERROR_INVALID_PRICE: "Debes ingresar un precio válido para la orden LIMIT.",
    ERROR_INVALID_QUANTITY: "La cantidad de acciones debe ser mayor a 0.",
    ERROR_LOW_INVESTMENT: "La inversión ingresada es demasiado baja para comprar al menos 1 acción.",
    ORDER_SENT: "Orden enviada",
    ORDER_ID: "ID:",
    ORDER_STATUS: "Estado:",
    STATUS_PENDING: "Pendiente",
    STATUS_FILLED: "Completada",
    STATUS_REJECTED: "Rechazada",
    STATUS_UNKNOWN: 'Estado desconocido',
    ERROR_MARKET_PENDING: "Error: Una orden MARKET no puede quedar en estado PENDING.",
    ORDER_FOR: "Hacer una orden para",
    ORDER_TYPE_SELECTION: "Tipo de orden",
    ORDER_SIDE: "Lado de la orden",
};
  